CREATE TABLE ITINERARY (
	ID			INTEGER,
	CREATED_AT	TEXT NOT NULL,
	COMPANY		TEXT NOT NULL,
	DEPARTURE	TEXT NOT NULL,
	ARRIVAL		TEXT NOT NULL,
	PRIMARY KEY(ID AUTOINCREMENT)
);

CREATE TABLE SERVICE (
	ID					INTEGER,
	ID_ITINERARY		INTEGER NOT NULL,
	CREATED_AT			TEXT NOT NULL,
	CODE				TEXT,
	DATE_TRIP			TEXT NOT NULL,
	TIME_DEPART			TEXT NOT NULL,
	TIME_ARRIVE			TEXT,
	DURATION_MINUTES	INTEGER,
	AVAILABLE_CLASSES	TEXT,
	CONSTRAINT FK_SERVICE_ITINERARY FOREIGN KEY(ID_ITINERARY) REFERENCES ITINERARY(ID),
	PRIMARY KEY(ID AUTOINCREMENT)
);
CREATE INDEX IDX_SERVICE_ITINERARY ON SERVICE(ID_ITINERARY);

CREATE TABLE FARE (
	ID			INTEGER,
	CREATED_AT	TEXT NOT NULL,
	ID_SERVICE	INTEGER NOT NULL,
	CLASS		TEXT NOT NULL,
	PRICE_CENTS	INTEGER NOT NULL,
	CONSTRAINT FK_FARE_SERVICE FOREIGN KEY(ID_SERVICE) REFERENCES SERVICE(ID),
	PRIMARY KEY(ID AUTOINCREMENT)
);
CREATE INDEX IDX_FARE_SERVICE ON FARE(ID_SERVICE);

CREATE TABLE "IGNAV_QUERIES" (
	"ID"			INTEGER,
	"CREATED_AT"	TEXT NOT NULL,
	"QUERY"			TEXT NOT NULL,
	"OUTCOME"		INTEGER NOT NULL,
	"CODE"			INTEGER,
	"MESSAGE"		TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
